address: 0.0.0.0:8080

telemetry:
  address: 0.0.0.0:10000

ingest:
  kafka:
    broker: kafka:9092

aggregation:
  clickhouse:
    address: clickhouse:9000

sink:
  minCommitCount: 1000
  maxCommitWait: 1s
  namespaceRefetch: 1s
  dedupe:
    enabled: true
    driver: redis
    config:
      expiration: 10m
      database: 1
      address: redis:6379

meters:
  - slug: grouped_count_meter
    description: Grouped Count Meter
    eventType: etype
    aggregation: COUNT
    groupBy:
      group1: $.group1
      group2: $.group2

  - slug: grouped_sum_meter
    description: Grouped Sum Meter
    eventType: etype
    aggregation: SUM
    valueProperty: $.value
    groupBy:
      group1: $.group1
      group2: $.group2

  - slug: grouped_avg_meter
    description: Grouped Average Meter
    eventType: etype
    aggregation: AVG
    valueProperty: $.value
    groupBy:
      group1: $.group1
      group2: $.group2

portal:
  enabled: false
  tokenSecret: this-isnt-secure
